export const customers = [
  {
    id: 1,
    gender: 'male',
    timeInStore: '15 mins',
    trolleyType: 'hand trolley',
    accompanied: 'single',
    dressColor: 'blue',
    threatPercentage: '5%',
    heatmap: '/heatmap_frames/frame_1.jpg',
  },
  {
    id: 2,
    gender: 'female',
    timeInStore: '30 mins',
    trolleyType: 'wheel trolley',
    accompanied: 'with someone',
    dressColor: 'red',
    threatPercentage: '3%',
    heatmap: '/heatmap_frames/frame_2.jpg',
  },
  {
    id: 3,
    gender: 'male',
    timeInStore: '45 mins',
    trolleyType: 'none',
    accompanied: 'single',
    dressColor: 'green',
    threatPercentage: '7%',
    heatmap: '/heatmap_frames/frame_3.jpg',
  },
  {
    id: 4,
    gender: 'female',
    timeInStore: '20 mins',
    trolleyType: 'hand trolley',
    accompanied: 'with someone',
    dressColor: 'yellow',
    threatPercentage: '2%',
    heatmap: '/heatmap_frames/frame_4.jpg',
  },
  {
    id: 5,
    gender: 'male',
    timeInStore: '10 mins',
    trolleyType: 'wheel trolley',
    accompanied: 'single',
    dressColor: 'black',
    threatPercentage: '4%',
    heatmap: '/heatmap_frames/frame_5.jpg',
  },
  {
    id: 6,
    gender: 'female',
    timeInStore: '25 mins',
    trolleyType: 'none',
    accompanied: 'with someone',
    dressColor: 'white',
    threatPercentage: '6%',
    heatmap: '/heatmap_frames/frame_6.jpg',
  },
  {
    id: 7,
    gender: 'male',
    timeInStore: '35 mins',
    trolleyType: 'hand trolley',
    accompanied: 'single',
    dressColor: 'blue',
    threatPercentage: '5%',
    heatmap: '/heatmap_frames/frame_7.jpg',
  },
  {
    id: 8,
    gender: 'female',
    timeInStore: '40 mins',
    trolleyType: 'wheel trolley',
    accompanied: 'with someone',
    dressColor: 'red',
    threatPercentage: '3%',
    heatmap: '/heatmap_frames/frame_8.jpg',
  },
  {
    id: 9,
    gender: 'male',
    timeInStore: '50 mins',
    trolleyType: 'none',
    accompanied: 'single',
    dressColor: 'green',
    threatPercentage: '7%',
    heatmap: '/heatmap_frames/frame_9.jpg',
  },
  {
    id: 10,
    gender: 'female',
    timeInStore: '15 mins',
    trolleyType: 'hand trolley',
    accompanied: 'with someone',
    dressColor: 'yellow',
    threatPercentage: '2%',
    heatmap: '/heatmap_frames/frame_10.jpg',
  },
  {
    id: 11,
    gender: 'male',
    timeInStore: '30 mins',
    trolleyType: 'wheel trolley',
    accompanied: 'single',
    dressColor: 'black',
    threatPercentage: '4%',
    heatmap: '/heatmap_frames/frame_11.jpg',
  },
  {
    id: 12,
    gender: 'female',
    timeInStore: '45 mins',
    trolleyType: 'none',
    accompanied: 'with someone',
    dressColor: 'white',
    threatPercentage: '6%',
    heatmap: '/heatmap_frames/frame_12.jpg',
  },
  {
    id: 13,
    gender: 'male',
    timeInStore: '20 mins',
    trolleyType: 'hand trolley',
    accompanied: 'single',
    dressColor: 'blue',
    threatPercentage: '5%',
    heatmap: '/heatmap_frames/frame_13.jpg',
  },
  {
    id: 14,
    gender: 'female',
    timeInStore: '10 mins',
    trolleyType: 'wheel trolley',
    accompanied: 'with someone',
    dressColor: 'red',
    threatPercentage: '3%',
    heatmap: '/heatmap_frames/frame_14.jpg',
  },
  {
    id: 15,
    gender: 'male',
    timeInStore: '25 mins',
    trolleyType: 'none',
    accompanied: 'single',
    dressColor: 'green',
    threatPercentage: '7%',
    heatmap: '/heatmap_frames/frame_15.jpg',
  },
  {
    id: 16,
    gender: 'female',
    timeInStore: '35 mins',
    trolleyType: 'hand trolley',
    accompanied: 'with someone',
    dressColor: 'yellow',
    threatPercentage: '2%',
    heatmap: '/heatmap_frames/frame_16.jpg',
  },
  {
    id: 17,
    gender: 'male',
    timeInStore: '40 mins',
    trolleyType: 'wheel trolley',
    accompanied: 'single',
    dressColor: 'black',
    threatPercentage: '4%',
    heatmap: '/heatmap_frames/frame_17.jpg',
  },
  {
    id: 18,
    gender: 'female',
    timeInStore: '50 mins',
    trolleyType: 'none',
    accompanied: 'with someone',
    dressColor: 'white',
    threatPercentage: '6%',
    heatmap: '/heatmap_frames/frame_18.jpg',
  },
  {
    id: 19,
    gender: 'male',
    timeInStore: '15 mins',
    trolleyType: 'hand trolley',
    accompanied: 'single',
    dressColor: 'blue',
    threatPercentage: '5%',
    heatmap: '/heatmap_frames/frame_19.jpg',
  },
  {
    id: 20,
    gender: 'female',
    timeInStore: '30 mins',
    trolleyType: 'wheel trolley',
    accompanied: 'with someone',
    dressColor: 'red',
    threatPercentage: '3%',
    heatmap: '/heatmap_frames/frame_20.jpg',
  },
  {
    id: 21,
    gender: 'male',
    timeInStore: '45 mins',
    trolleyType: 'none',
    accompanied: 'single',
    dressColor: 'green',
    threatPercentage: '7%',
    heatmap: '/heatmap_frames/frame_21.jpg',
  },
  {
    id: 22,
    gender: 'female',
    timeInStore: '20 mins',
    trolleyType: 'hand trolley',
    accompanied: 'with someone',
    dressColor: 'yellow',
    threatPercentage: '2%',
    heatmap: '/heatmap_frames/frame_22.jpg',
  },
  {
    id: 23,
    gender: 'male',
    timeInStore: '10 mins',
    trolleyType: 'wheel trolley',
    accompanied: 'single',
    dressColor: 'black',
    threatPercentage: '4%',
    heatmap: '/heatmap_frames/frame_23.jpg',
  },
];

export type Customer = {
  id: number;
  gender: string;
  timeInStore: string;
  trolleyType: string;
  accompanied: string;
  dressColor: string;
  threatPercentage: string;
  heatmap: string;
};

export const stores = [
  {
    name: 'ICA Varnhem',
    address: 'Östra Förstadsgatan 50, 212 12 Malmö',
    image: '/maps/ica_varnhem.png',
  },
  {
    name: 'ICA Kvantum',
    address: 'Norra Kungsgatan 8, 642 37 Flen',
    image: '/maps/ica_kvantum_flen.png',
  },
  {
    name: 'ICA Supermarket',
    address: 'Hornsgatan 146, A-B, 117 28 Stockholm',
    image: '/maps/ica_supermarket_stockholm.png',
  },
  {
    name: 'Stkhlm Warehouse',
    address: 'Tavastgatan 34, 118 24 Stockholm',
    image: '/maps/warehouse.png',
  },
];
