import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Michroma as FontSans } from 'next/font/google';
import { cn } from '@/lib/utils';
import Header from '@/components/dashboard/header';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
  weight: '400',
  style: 'normal',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn('min-h-screen  font-sans antialiased', fontSans.variable)}
      >
        <div className="h-16 flex  items-center justify-between w-full border-b border-neutral-400 bg-neutral-100">
          <Header />
        </div>
        {children}
      </body>
    </html>
  );
}
